### ISSUE TITLE
re-frame interceptors without the global mutable state

### ISSUE THREAD

**Issue by chpill** [roman01la/citrus#10]
Hi,

We had a little discussion last week on reddit about re-frame interceptors and I said I was going to open an issue the day after... Sorry for the delay!

Well I dug up so deep into re-frame interceptors that I ended up making a fork of re-frame that kind of supports rum, and without global state https://github.com/chpill/re-frankenstein.

The https://github.com/chpill/re-frankenstein/blob/master/src/re_frame/frank.cljs namespace was derived from your reconciler design. It shows how to use re-frame interceptors without the global mutable state.

**Comment by roman01la** [comment]
@chpill Hi! I'll take a look when I get back from vacation. Thanks!

**Comment by roman01la** [comment]
Sorry for not responding here. I guess co-effects kind of solving this problem?

**Comment by chpill** [comment]
I have yet to use co-effects, so i do not really now... Anyway, this was more about creating a discussion on the differences between scrum an re-frame, not really an issue :) I'm gonna close it now. I'm not using re-frankenstein anymore, it was a fun experiment, but in the end, I felt all the extra-complexity did not bring a lot to the table compared to scrum.
