### ISSUE TITLE
Enhancement: integration with dev tools

### ISSUE THREAD

**Issue by tkachenko1503** [roman01la/citrus#12]
Hello @roman01la 
Thanks for this project

I tried out scrum and i like it
But for me there is some lack of integration with developer tools (aka redux dev tools)
It would be nice to have the ability to use debugger or logger for events and state changes
or maybe time travel debugger

Maybe i miss something and there is some tools for that?

**Comment by roman01la** [comment]
@tkachenko1503 Hi. Thanks! Current architecture doesn't provide core capabilities for integrating development tooling, but you can always hook into state atom with

**Comment by roman01la** [comment]
I'll drop an example later here

**Comment by tkachenko1503** [comment]
OK! Thanks

**Comment by roman01la** [comment]
I just published a package with very basic tooling https://clojars.org/org.roman01la/scrum.devtools

It provides console logger and time-traveling UI with state diffs and current state visualization.

Add to project dependencies: `[org.roman01la/scrum.devtools "0.1.0-SNAPSHOT"]`

In your code, where you create `state` atom, do the following to setup devtools:

Require `[scrum.devtools.logger :as logger]` and `[scrum.devtools.ui :as dui]`

```clojure
;; this is your app state
(def state (atom {}))

(when ^boolean goog.DEBUG ;; <= only in dev mode
  (logger/attach! state) ;; <= setup logger
  (dui/mount! state (dom/getElement "debug"))) ;; <= mount devtools UI into the DOM

;; setup reconciler, etc.
;; ...
```

**Comment by escherize** [comment]
The repo your clojars link points to is gone.

Is the scrum.devtools repo available elsewhere?

**Comment by roman01la** [comment]
@escherize no, it's not public. TBH there's nothing super exciting, you can easily hook into atom state and log state changes  :)
