### ISSUE TITLE
Redux-like middlewares ?

### ISSUE THREAD

**Issue by DjebbZ** [roman01la/citrus#15]
Hi,

Thinking about our discussion at EuroClojure Berlin, I finally think middlewares could be useful. Indeed watching state changes is nice but doesn't allow logging/watching events and doing more advanced stuff.

So starting a discussion about them.

**Comment by DjebbZ** [comment]
Simple trick to watch state changes:

``` clojure
(add-watch reconciler :debug
           (fn [k ref oldv newv]
              (prn "[debug]   " (clojure.data/diff oldv newv)) 
```

The only missing thing is the citrus event that triggered the underlying `swap!`.

**Comment by roman01la** [comment]
Closing this. I think if we need it, we should go with interceptors as in re-frame

**Comment by DjebbZ** [comment]
Agree. I'm using interceptors in pedestal and they're the same concept, have to say the model is really flexible
