### ISSUE TITLE
Rename to strum?

### ISSUE THREAD

**Issue by shaunlebron** [roman01la/citrus#16]
**ST**ate manage for __Rum__?

@escherize was telling me about this library, and I thought Scrum was a confusing name :)

**Comment by roman01la** [comment]
I like this confusing name TBH :)
P.S.
SCRUM stands for "State Coordination for RUM"

**Comment by shaunlebron** [comment]
I think a name should be more than clever, right?  The acronym is clever, but confusing and I think that makes it bad.  And since we both care about the ClojureScript experience, naming is a part of how we make the experience better (which is why I'm actually renaming Parinfer soon!)

In the context of how I heard it in conversation with Bryan:

> Bryan: Have you heard of Scrum?

> Me (internally): Yeah, it's that annoying standup thing I gotta do every morning that no one does correctly. :D

(🚲 🏚 )

**Comment by roman01la** [comment]
Ok, I'm all open to make it more accessible. Do you want to propose possible migration plan?

**Comment by shaunlebron** [comment]
Thanks for being open to this!  Some thoughts on migrating:

### Clojars

```
old: [org.roman01la/scrum "2.3.0-SNAPSHOT"]
new: [org.roman01la/strum "3.0.0"]
```

1. __Publish new package name__: Some precedent here—[om] was renamed to [org.omcljs/om] some time ago, and both are still available, with only the latter receiving updates.  Only publish updates to the new name, and leave the old as is.
1. __Increment major version__: Since the namespace rename constitutes a breaking change, I'm thinking we have to increment the major version number.

[om]:https://clojars.org/om
[org.omcljs/om]:https://clojars.org/org.omcljs/om

### Repos

1. Renaming the github repo should be fine since all old urls will be redirected, of course.
1. Rename/migrate [scrum-ssr-example] and migrate [cljs-rum-realworld-example-app]

[scrum-ssr-example]:https://github.com/roman01la/scrum-ssr-example
[cljs-rum-realworld-example-app]:https://github.com/roman01la/cljs-rum-realworld-example-app

### Users

1. Tell users to `s/scrum/strum/g` relevant files.
2. Put a notice at the top of the repo readme, _above_ the title.
3. Post on clojurescript mailing list and twitter.
4. [Rename slack channel](https://get.slack.help/hc/en-us/articles/201654073-Rename-a-channel)

If we want to be extra proactive (probably not necessary):

1. [Search org.roman01la/scrum on github](https://github.com/search?q=org.roman01la%2Fscrum&type=Code&utf8=%E2%9C%93) and send PRs.
1. For projects not on github, create a reasonably safe rename script for them?

**Comment by oakmac** [comment]
I would like to propose the name **citrus** for this library.

I am a big fan of Rum the library, as well as Rum the liquor. In almost every classic Rum-based cocktail, citrus is used as an ingredient to 1) pair with the sugar-based flavor of the Rum and 2) smooth the harshness of the alcohol flavor.

I think it is very fitting for how this library pairs with Rum.

**Comment by roman01la** [comment]
@oakmac You just sold me this name 😀

**Comment by roman01la** [comment]
@shaunlebron Thank you very much for such detailed plan! I'll follow it when I'll have time to start migration process.

**Comment by roman01la** [comment]
most of the migration path is done, follow tracking issue here #17
