### ISSUE TITLE
`update-in`-style state updates?

### ISSUE THREAD

**Issue by ojw** [roman01la/citrus#24]
It looks like updates using the `:state` effect replaces the entire state for the controller whose event returns the `:state` effect.  I'm interested in figuring out how to perform a limited, `assoc-in` or `update-in` style update instead of clobbering the entire state for the controller.

One can write something like an `update-in` as an event handler, by taking the state argument, updating part of it, and emitting a `:state` effect to set to the `update-in`d state.  However, if two such events are created at the same time, only one will work, because they all see and update the same starting state.

So it would be better to write an `:update-in` effect.  From looking at the source, I'm not sure how to do that.  It looks like `:state` is specially handled, at least in master.  In particular, `Reconciler`s don't implement the `swap` interface, and I don't seem to be able just grab the `(:state reconciler)`.

Am I overlooking an easy way to write `:update-in` as an effect?

**Comment by roman01la** [comment]
Not sure what do you mean exactly. The controller gives you a part of global state, you can produce a new state with standard Clojure functions and return it back in `:state` effect.

**Comment by ojw** [comment]
Alternately, either implementing the `atom` interface for the reconciler, or making the reconciler a `defrecord` instead of `deftype`, would let users easily write their own implementation of those effects.  As is, it's not obvious to me how to implement them.

**Comment by mbutlerw** [comment]
Was this not fixed by https://github.com/roman01la/citrus/commit/b94a679676c3420f06fa95973638c40055d48537?

**Comment by roman01la** [comment]
@mbutlerw I guess you are right. Closing it for now. @ojw Please let me if the problem still remains
