### ISSUE TITLE
js/setTimeout for function using dispatch-sync!

### ISSUE THREAD

**Issue by claj** [roman01la/citrus#29]
Is there any way to use a `setTimeout` with a citrus reconciler.

When we create a timeout on the form `#(citrus/dispatch! reconciler :event args)` it seems like it wont touch the reconciler state.

The event handlers can, of course, use the reconciler with dispatches.

**Comment by claj** [comment]
Sorry for being unclear.

We have an application with a micro interaction (a sign up form) with state transition that should take place a certain time after another thing, so after the user has filled in his or hers email adress and pressed submit, it looks something like this (I take out parts of the code and make it more clear)

```
[:button 
{:on-click #(citrus/dispatch! reconciler :offer :submit @the-email-address-backed-in-an-input-field)}
       "Sign up"]
```

which triggers a handler 

```
(defmethod control :submit [reconciler args state]
  (js/setTimeout #(citrus.core/dispatch-sync! reconciler :offer :form-submitted) 1000)
  (let [next-state (assoc state :submit-state :show-thank-you :email (first args)]
    {:state next-state
    ;; side effects for sending the data to server
    }))
```

where we want to trigger the method `:form-submitted` after 1000 ms.

```
(defmethod control :form-submitted [_ _ state]
  (let [next-state (assoc state :submit-state :form-submitted)]
    {:state next-state}))
```

For some reason the `citrus/dispatch-sync!` call in the :submit-handler seems not to trigger correctly. This doesn't work with `citrus/dispatch!` either.

Of course this could be something we do wrong in the rest of our code (the code above is slightly adapted.

My questions are: 

a) Is there anything that theorically prevents us from using `js/setTimeout` to dispatch new events into citrus state management?

b) Is it idiomatic to dispatch new events from inside controllers to achieve what we want to do above?

Apart from that Citrus makes it very easy to structure or app with Rum!

**Comment by roman01la** [comment]
Thanks for clarifying.

First, Citrus provides a mechanism to handle effects, such as `:state` and others. In your case I'd suggest to implement `:timeout` effect handler. See [“Side effects”](https://github.com/roman01la/citrus#side-effects) section for reference. This would be an idiomatic Citrus way of handling side effects.

```clojure
(defmethod control :submit [reconciler args state]
  (let [next-state (assoc state :submit-state :show-thank-you :email (first args)]
    {:state next-state
     :timeout-dispatch [1000 [:offer :form-submitted]]
    ;; side effects for sending the data to server
    }))

(defn timeout-dispatch [reconciler _ effect]
  (let [[t [ctrl event]] effect]
    (js/setTimeout #(citrus/dispatch! reconciler ctrl event %) t)))

(defonce reconciler
  (citrus/reconciler
    {:state
     (atom {}) ;; application state
     :controllers
     {:counter control} ;; controllers
     :effect-handlers
     {:timeout-dispatch timeout-dispatch}})) ;; effect handlers
```

Second, while the above approach is not required, but recommended, your code should work as well. I'm gonna test it on my side.

**Comment by claj** [comment]
Thank you very, very much!
