### ISSUE TITLE
Controller/control function will fail unless it is a multimethod

### ISSUE THREAD

**Issue by hammonba** [roman01la/citrus#36]
the committ `add dispatch assertions` 

https://github.com/roman01la/citrus/commit/78195820136d30e662e30f7361e7952f5692a025

means that controlller/control functions will blow up with a 
`Uncaught Error: No protocol method IMultiFn.-methods defined for type function:`
 if they are not a multimethod

Is this a bug or a feature?

I have a  codebase that was using a simple control function to wrap a multimethod call that broke.
Was this code in violation of the citrus application structure (and therefore deserved to fail)?
Or is it an unintended oversight?

**Comment by roman01la** [comment]
@hammonba I think there's nothing wrong in using a function. This change was a part of UX improvement, but I didn't expect someone to pass a function there bc I myself never did that. I'm gonna remove this assert. Thanks!

**Comment by roman01la** [comment]
should be fine in `3.2.1`
